Fixed issues related to single node deployment
Ontotext-AD/terraform-aws-graphdb pull request #61
Opened 2024-07-16 06:40 UTC by viktor-ribchev

## Description

Fixed issues related to single node deployment

## Related Issues

GDB-10523

## Changes

* Removed unused variables
* Fixed graphdb.properties values for single node deployment
* Removed calculation of `lb_tls_enabled` in the LB module as it is calculated in the main.tf
* Replaced `monitoring_route53_healtcheck_fqdn_url` with `graphdb_external_address` as it is the same URL.
* Removed `monitoring_route53_healtcheck_fqdn_url` variable
* Introduced new variable `graphdb_external_address`

## Screenshots (if applicable)

N/A

## Checklist

- [X] I have tested these changes thoroughly.
- [X] My code follows the project's coding style.
- [X] I have added appropriate comments to my code, especially in complex areas.
- [X] All new and existing tests passed locally.

2024-07-16 06:56 UTC, simeonzhekofff approved these changes
LGTM

2024-07-16 09:06 UTC, mihailradkov requested changes

2024-07-16 09:06 UTC, mihailradkov commented on modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl
> +graphdb.external-url.enforce.transactions=true
Could you add a note/comment somewhere **why** this enforcement is needed? It would be helpful for future maintainers.

2024-07-16 10:37 UTC, viktor-ribchev commented on main.tf
> +  calculated_http_string_type = local.lb_tls_enabled == true ? "HTTPS" : "HTTP"
Should be uppercase here, otherwise not accepted for the type of resource "aws_route53_health_check" "graphdb_availability_check"

2024-07-16 10:37 UTC, viktor-ribchev commented on main.tf
> +  lb_tls_enabled                = local.lb_tls_enabled
If you provide TLS Certificate ARN then we assume that the TLS is enabled.

2024-07-16 10:37 UTC, viktor-ribchev commented on modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl
> +NODE_COUNT=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names ${name} --query "AutoScalingGroups[0].DesiredCapacity" --output text)
in the future

2024-07-16 10:47 UTC, mihailradkov commented on main.tf
> +  calculated_http_string_type = local.lb_tls_enabled == true ? "HTTPS" : "HTTP"
Hence my `Make 'em upper case where needed.`

2024-07-16 10:48 UTC, mihailradkov commented on main.tf
> +  lb_tls_enabled                = local.lb_tls_enabled
So the lb module now avoids calculating this on its own in favor of a superfluous variable.

2024-07-16 10:55 UTC, viktor-ribchev commented on main.tf
> +  lb_tls_enabled                = local.lb_tls_enabled
It's not a superfluous variable, it is required to have TLS termination on LB level, calculating the lb_tls_enabled based on lb_tls_certificate_arn is better than to have two variables manually set.

2024-07-17 06:06 UTC, mihailradkov commented on variables.tf
> +  description = "External address where GraphDB will be accessed"
Update the description to make it more clear as it is still relevant for the old var name.

2024-07-17 06:06 UTC, mihailradkov commented on modules/graphdb/variables.tf
> +  description = "External address HTTP string type"
`external_address_protocol` ?

2024-07-17 06:06 UTC, mihailradkov commented on modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl
> +PROTOCOL=$(echo "${external_address_http_string_type}" | awk '{print tolower($0)}')
This `tolower` can be done with Terraform when providing the variable to the user scripts.

2024-07-17 06:10 UTC, mihailradkov commented on main.tf
> +  lb_tls_enabled                = local.lb_tls_enabled
The real issue seems to be that we cannot adequately perform `count` with a string variable check.

2024-07-17 06:22 UTC, mihailradkov approved these changes

2024-07-17 06:28 UTC, merged